  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: DMN AWS Lambda

  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:

    DMNServerlessFunction:
      Type: AWS::Serverless::Function
      Properties:
        Description: KYC DMN Kogito with AWS Lambda 
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java11
        CodeUri: ../../../target/function.zip
        MemorySize: 512
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 15
        Tags: 
          - Key: "net.a.g:tech"
            Value: "java"
          - Key: "net.a.g:tech-version"
            Value: "11"
          - Key: "net.a.g:standard"
            Value: "dmn"
          - Key: "net.a.g:framework"
            Value: "quarkus"
          - Key: "net.a.g:app-version"
            Value: "1.0.0"
          - Key: "net.a.g:spec-version"
            Value: "1.0.0"
        # Events:
        #   HttpApiEvent:
        #     Type: HttpApi

    # DMNApiGatewayApi:
    #   Type: AWS::ApiGatewayV2::Api
    #   Description: DMN ApiGateway Api
    #   ProtocolType: HTTP
    #   DependsOn:
    #     - DMNServerlessFunction
