name: Build and Deploy DMN Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/**'
      - 'pom.xml'

env:
  AWS_REGION: eu-west-1
  AWS_S3_BUCKET_NAME: dmn-lambda
  AWS_STACK_NAME: dmn-lambda

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        id: checkout-git
        uses: actions/checkout@v3

      - name: Install java
        id: install-java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'maven'

      - name: Setup SAM
        id: setup-sam      
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credential
        id: configure-aws      
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build with Maven
        id: build-maven      
        run: mvn clean package

      - name: Check or Create S3 Bucket
        id: check-s3-bucket
        run: aws s3api head-bucket  --bucket ${{ env.AWS_S3_BUCKET_NAME }} || aws s3 mb s3://${{ env.AWS_S3_BUCKET_NAME }} 

      - name: Deploy Lambda
        id: deploy-lambda      
        run: sam deploy -t src/main/aws/sam.gh.yaml --region ${{ env.AWS_REGION }} --capabilities CAPABILITY_IAM --no-progressbar --s3-bucket ${{ env.AWS_S3_BUCKET_NAME }} --stack-name ${{ env.AWS_STACK_NAME}} --disable-rollback --no-confirm-changeset --s3-prefix ${{ env.AWS_STACK_NAME}} 
