on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  S3_URI: dmn-lambda-test

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'maven'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build with Maven
        run: mvn clean package

      - name: Check S3 Bucket ${{ env.S3_URI }}
        run: aws s3api head-bucket  --bucket ${{ env.S3_URI }} 