on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  S3_BN: dmn-lambda-test
  AWS_SN: dmn-lambda

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'maven'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build with Maven
        run: mvn clean package

      - name: Check S3 Bucket
        run: aws s3api head-bucket  --bucket ${{ env.S3_BN }} 

      - name: Create S3 Bucket  
        if: failure()
        run: aws s3 mb s3://${{ env.S3_BN }} 

      - name: Deploy Lambda
        run: sam deploy -t src/main/aws/sam.jvm.yaml  --region ${{ env.AWS_REGION }} --capabilities CAPABILITY_IAM --no-progressbar --s3-bucket ${{ env.S3_BN }}   --stack-name ${{ env.AWS_SN}}   --disable-rollback --no-confirm-changeset  --s3-prefix ${{ env.AWS_SN}} 
